import { ListView, VerticalBox, Palette, Button } from "std-widgets.slint";
import { FileTable, Download } from "../widgets/filetable.slint";
import { GbPreviewData} from "../widgets/gb-search-card.slint";

export component FileRow {
    in property <int> idx;
    in property <Download> data;

    callback clicked <=> download.clicked;
    Rectangle {
        background: mod(idx, 2) == 0 ? Palette.alternate-background : Palette.background;
        HorizontalLayout {
            Text {
                text: data.name;
            }

            download := Button {
                min-width: 2000px;
                width: 20%;
                text: "Download";
            }
        }
    }
}

export component ModFiles inherits Dialog {
    in property <GbPreviewData> gb-item:{
        image: @image-url("../assets/test-preview.jpg"),
        name:"Onneb's Song Pack",
        author: "Onneb",
        item-type:"Mod"
    };
    in-out property <[Download]> files: [{ name:"Test" }];

    VerticalBox {
        HorizontalLayout {
            Image {
                source: gb-item.image;
                height: 124px;
                width: 220px;
            }

            VerticalLayout {
                Text {
                    text: gb-item.name;
                    font-size: 20px;
                    horizontal-alignment: center;
                }

                Text {
                    horizontal-alignment: center;
                    font-size: 14px;
                    text: "Author: " + gb-item.author;
                }
            }
        }
        Text {
            text: "Files:";
        }
        ListView {
            for file[idx] in files: FileRow { }
        }
    }
}
