// SPDX-FileCopyrightText: 2022 flovansl <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Palette, Radius } from "../styling.slint";

export component PopupBorder inherits Rectangle {
    background: Palette.background;
    border_radius: Radius.medium;
    border_width: 1px;
    border_color: Palette.border;
    clip: true;
    drop_shadow_color: Palette.shadow;
    drop_shadow_blur: 16px;
    drop_shadow_offset_y: 4px;
}

export component Popup inherits PopupWindow {
    in property <length> min-win-height;
    in property <length> min-win-width;

    PopupBorder {
        min-height: root.min-win-height;
        min-width: root.min-win-width;
        @children
    }
}
