import {Palette as CosmicPalette} from "../styling.slint";

export component StateLayerBase {
    in property <length> border-radius <=> overlay.border-radius;
    in property <bool> has-focus;
    in property <bool> pressed;
    in property <bool> has-hover;
    in property <bool> checked;
    in property <bool> enabled: true;
    in property <length> focus-border-margin: 3px;
    out property <brush> background <=> overlay.background;

    @children

    overlay := Rectangle {}

    if (root.has-focus && root.enabled) : Rectangle {
        width: root.width + root.focus-border-margin * 2;
        height: root.height + root.focus-border-margin * 2;
        border-width: 1px;
        border-radius: root.border-radius + root.focus-border-margin;
        border-color: CosmicPalette.state-focus;
    }

    states [
        pressed when root.pressed : {
            overlay.background: CosmicPalette.state-pressed;
        }
        hover when root.has-hover : {
            overlay.background: CosmicPalette.state-hover;
        }
        checked when root.checked : {
            overlay.background: CosmicPalette.state-selected;
        }
    ]
}
