import { Palette } from "std-widgets.slint";
import { EditorPalette, EditorAnimationSettings } from "../styling.slint";
import { StateLayerBase } from "state-layer-base.slint";

export component StateLayer inherits TouchArea {
    in property <length> border-radius <=> base.border-radius;
    out property <bool> has-focus: focus-scope.has-focus;
    in-out property <bool> checked;
    in property <length> focus-boder-margin <=> base.focus-border-margin;

    forward-focus: focus-scope;

    focus-scope := FocusScope {
        x: 0;
        width: 0; // Do not react on clicks
        enabled <=> root.enabled;

        key-pressed(event) => {
            if (event.text == " " || event.text == "\n") {
                root.clicked();
                 return accept;
            }

            return reject;
        }
    }

   base := StateLayerBase {
        width: 100%;
        height: 100%;
        has-focus: root.has-focus;
        pressed: root.pressed;
        has-hover: root.has-hover;
        checked: root.checked;
        enabled: root.enabled;

        @children
   }
}