[package]
name = "divamods"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.8.3"
regex = "1.10.5"
curl = "0.4.46"
json = "0.12.4"
sonic-rs = "0.3.8"
serde = { version = "1.0.203", features = ["derive"] }