[package]
name = "rust4diva"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.28.1"
regex = "1.10.5"
curl = "0.4.46"
json = "0.12.4"
sonic-rs = "0.3.8"
serde = { version = "1.0.203", features = ["derive"] }
env_logger = "0.11.3"
eframe = { version = "0.28.1" }
toml = "0.8.14"
dirs = "5.0.1"
keyvalues-parser = "0.2.0"
egui_extras = "0.28.1"
compress-tools = "0.15.0"
reqwest = "0.12.5"
tokio = { version = "1.38.0", features = ["full"] }
interprocess = { version = "2.2.0", features = ["tokio"] }
tokio-macros = { version = "0.2.0-alpha.6" }
slint = "1.6.0"



[build-dependencies]
slint-build = "1.6"