[package]
name = "rust4diva"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.5"
curl = "0.4.46"
json = "0.12.4"
sonic-rs = "0.3.8"
serde = { version = "1.0.203", features = ["derive"] }
env_logger = "0.11.3"
toml = "0.8.14"
dirs = "5.0.1"
keyvalues-parser = "0.2.0"
compress-tools = "0.15.0"
reqwest = { version = "0.12.5", features = ["stream"] }
reqwest-streams = "0.7.0"
tokio = { version = "1.38.0", features = ["full"] }
interprocess = { version = "2.2.0", features = ["tokio"] }
tokio-macros = { version = "0.2.0-alpha.6" }
slint = "1.6.0"
slint-interpreter = "1.7.0"
futures-util = "0.3.30"
cfg-if = "1.0.0"


[target.'cfg(windows)'.dependencies]
winreg = "0.52.0"


[build-dependencies]
slint-build = "1.6"