export component CtxMenuItem {
    in property <bool> selected;
    in property <bool> has_drag_hover;
    in property <bool> enabled <=> touch_area.enabled;
    in property <length> border_radius <=> background.border_radius;
    out property <length> mouse_x <=> touch_area.mouse_x;
    out property <length> mouse_y <=> touch_area.mouse_y;
    out property <length> pressed_x <=> touch_area.pressed_x;
    out property <length> pressed_y <=> touch_area.pressed_y;
    out property <bool> has_hover <=> touch_area.has_hover;
    out property <bool> pressed <=> touch_area.pressed;
    in_out property <brush> background;

    callback clicked <=> touch_area.clicked;
    callback pointer_event <=> touch_area.pointer_event;
    callback moved <=> touch_area.moved;

    touch_area := TouchArea {
        mouse-cursor: MouseCursor.pointer;
    }

    background := Rectangle {
        background: root.background;

        @children
    }
}