import { ListView, VerticalBox, ProgressIndicator,  Button, Palette } from "std-widgets.slint";
import { StateLayerBase } from "../components/state-layer-base.slint";
import { CosmicFontSettings} from "../styling/cosmic-styling.slint";
import { TableViewColumn, TableViewCell, TableViewRow} from "./common-table.slint";
import { TableViewCellNoTouch } from "common-table.slint";
import { Download} from "../diva-types.slint";
import { GameBananaLogic } from "../applogic.slint";
// import {Icons} from ""



export component FileTableRow inherits Rectangle {
    in property <bool> selected;
    in property <bool> even;
    callback pointer-event(/* event */ PointerEvent, /* absolute mouse position */ Point);
    min-width: layout.min-width;
    min-height: max(24px, layout.min-height);
    background: root.even ? Palette.control-background : transparent;
    StateLayerBase {
        checked: root.selected;
        focus-boder-margin: 0;
        border-radius: root.border-radius;
        // pressed: touch-area.pressed;
        // has-hover: touch-area.has-hover;
    }

    layout := HorizontalLayout {
        @children
    }
}

export component FileTable {
    in-out property <[Download]> files;
    in-out property <[TableColumn]> columns;
    in-out property <int> current-row: -1;
    out property <int> current-sort-column: -1;
    callback row-pointer-event(int/* row-index */, PointerEvent/* event */, Point/* absolute mouse position */);
    callback current-row-changed(int/* current-row */);
    callback sort-ascending(/* column-index */ int);
    callback sort-descending(/* column-index */ int);

    private property <length> min-header-height: 32px;
    private property <length> item-height: scroll-view.viewport-height / files.length;
    private property <length> current-item-y: scroll-view.viewport-y + current-row * item-height;

    private property <length> e: self.width / root.columns.length;

    public pure function get-size-next-unit(size: int) -> int {
        return (size / 1024);
    }

    public function set-current-row(index: int) {
        if (index < 0 || index >= files.length) {
            return;
        }
        current-row = index;
        current-row-changed(current-row);

        if (current-item-y < 0) {
            scroll-view.viewport-y += 0 - current-item-y;
        }
        if (current-item-y + item-height > scroll-view.visible-height) {
            scroll-view.viewport-y -= current-item-y + item-height - scroll-view.visible-height;
        }
    }

    function sort(index: int) {
        if (root.current-sort-column != index) {
            root.columns[root.current-sort-column].sort-order = SortOrder.unsorted;
        }
        if (root.columns[index].sort-order == SortOrder.ascending) {
            root.columns[index].sort-order = SortOrder.descending;
            root.sort-descending(index);
        } else {
            root.columns[index].sort-order = SortOrder.ascending;
            root.sort-ascending(index);
        }

        root.current-sort-column = index;
    }

    min-width: 400px;
    min-height: 200px;
    horizontal-stretch: 1;
    vertical-stretch: 1;
    accessible-role: table;
    forward-focus: focus-scope;

    VerticalLayout {
        Rectangle {
            clip: true;
            vertical-stretch: 0;
            min-height: root.min-header-height;
            background: Palette.control-background;

            header-layout := HorizontalLayout {
                width: max(self.preferred-width, parent.width);
                x: scroll-view.viewport-x;
                padding-right: 6px;
                min-height: root.min-header-height;

                for column[index] in root.columns: TableViewColumn {
                    sort-order: column.sort-order;
                    horizontal-stretch: column.horizontal-stretch;
                    min-width: max(column.min-width, column.width);
                    preferred-width: self.min-width;
                    max-width: (index < columns.length && column.width >= 1px) ? max(column.min-width, column.width) : 100000px;

                    clicked => {
                        root.sort(index);
                    }

                    adjust-size(diff) => {
                        column.width = max(1px, self.width + diff);
                    }

                    Text {
                        vertical-alignment: center;
                        text: column.title;
                        font-weight: CosmicFontSettings.body.font-weight;
                        font-size: CosmicFontSettings.body.font-size;
                        color: Palette.foreground;
                        overflow: elide;
                    }
                }
            }

            // padding: 5px;

        }

        scroll-view := ListView {
            for file[idx] in root.files: FileTableRow {

                selected: idx == root.current-row;
                even: mod(idx, 2) == 0;

                pointer-event(pe, pos) => {
                    root.row-pointer-event(idx, pe, {
                        x: pos.x - root.absolute-position.x,
                        y: pos.y - root.absolute-position.y,
                    });
                }

                TableViewCell {
                    horizontal-stretch: columns[0].horizontal-stretch;
                    min-width: max(columns[0].min-width, columns[0].width);
                    preferred-width: self.min-width;
                    max-width: (2 < columns.length && columns[0].width >= 1px) ? max(columns[0].min-width, columns[0].width) : 100000px;

                    Rectangle {
                        name-text := Text {
                            width: 100%;
                            height: 100%;
                            overflow: elide;
                            vertical-alignment: center;
                            text: file.name;
                            font-weight: CosmicFontSettings.body.font-weight;
                            font-size: CosmicFontSettings.body.font-size;
                            color: mod(idx, 2) == 0 ? Palette.control-foreground : Palette.foreground;

                            states [
                                selected when idx == root.current-row: {
                                    name-text.color: Palette.accent-background;
                                }
                            ]
                        }
                    }
                }

                TableViewCell {
                    horizontal-stretch: columns[1].horizontal-stretch;
                    min-width: max(columns[1].min-width, columns[1].width);
                    preferred-width: self.min-width;
                    max-width: (1 < columns.length && columns[1].width >= 1px) ? max(columns[1].min-width, columns[1].width) : 100000px;
                    // width: root.column_sizes[1];
                    Rectangle {
                        bytes-text := Text {
                            width: 100%;
                            height: 100%;
                            overflow: elide;
                            vertical-alignment: center;
                            text: root.get-size-next-unit(root.get-size-next-unit(file.size)) + "MBs";
                            font-weight: CosmicFontSettings.body.font-weight;
                            font-size: CosmicFontSettings.body.font-size;
                            color: mod(idx, 2) == 0 ? Palette.control-foreground : Palette.foreground;

                            states [
                                selected when idx == root.current-row: {
                                    bytes-text.color: Palette.accent-background;
                                }
                            ]
                        }
                    }
                }

                if columns.length >= 3:
                TableViewCell {
                    horizontal-stretch: columns[2].horizontal-stretch;
                    min-width: max(columns[2].min-width, columns[2].width);
                    preferred-width: self.min-width;
                    max-width: (2 < columns.length && columns[2].width >= 1px) ? max(columns[2].min-width, columns[2].width) : 100000px;
                    // width: root.column_sizes[2];
                    if file.failed == false: ProgressIndicator {
                        indeterminate: false;
                        progress: file.progress / file.size;
                    }
                    if file.failed == true: Text {
                        text: "Download FAILED";
                    }
                }
                if columns.length >= 4: TableViewCellNoTouch {
                    horizontal-stretch: columns[2].horizontal-stretch;
                    min-width: max(columns[2].min-width, columns[2].width);
                    preferred-width: self.min-width;
                    max-width: (2 < columns.length && columns[2].width >= 1px) ? max(columns[2].min-width, columns[2].width) : 100000px;
                    Button {
                        text: "Download";
                        clicked => {
                            debug(file.name);
                            GameBananaLogic.download(file);
                        }
                    }
                }
            }
        }
    }

    focus-scope := FocusScope {
        x: 0;
        width: 0;
        // Do not react on clicks

        key-pressed(event) => {
            if (event.text == Key.UpArrow) {
                root.set-current-row(root.current-row - 1);
                return accept;
            } else if (event.text == Key.DownArrow) {
                root.set-current-row(root.current-row + 1);
                return accept;
            }
            reject
        }
    }
}

export component GbFileTable {
    in-out property <[Download]> files;
    in-out property <[TableColumn]> columns;
    in-out property <int> current-row: -1;
    out property <int> current-sort-column: -1;
    callback row-pointer-event(int/* row-index */, PointerEvent/* event */, Point/* absolute mouse position */);
    callback current-row-changed(int/* current-row */);
    callback sort-ascending(/* column-index */ int);
    callback sort-descending(/* column-index */ int);

    private property <length> min-header-height: 32px;
    private property <length> item-height: scroll-view.viewport-height / files.length;
    private property <length> current-item-y: scroll-view.viewport-y + current-row * item-height;

    private property <length> e: self.width / root.columns.length;

    public pure function get-size-next-unit(size: int) -> int {
        return (size / 1024);
    }

    public function set-current-row(index: int) {
        if (index < 0 || index >= files.length) {
            return;
        }
        current-row = index;
        current-row-changed(current-row);

        if (current-item-y < 0) {
            scroll-view.viewport-y += 0 - current-item-y;
        }
        if (current-item-y + item-height > scroll-view.visible-height) {
            scroll-view.viewport-y -= current-item-y + item-height - scroll-view.visible-height;
        }
    }

    function sort(index: int) {
        if (root.current-sort-column != index) {
            root.columns[root.current-sort-column].sort-order = SortOrder.unsorted;
        }
        if (root.columns[index].sort-order == SortOrder.ascending) {
            root.columns[index].sort-order = SortOrder.descending;
            root.sort-descending(index);
        } else {
            root.columns[index].sort-order = SortOrder.ascending;
            root.sort-ascending(index);
        }

        root.current-sort-column = index;
    }

    min-width: 400px;
    min-height: 200px;
    horizontal-stretch: 1;
    vertical-stretch: 1;
    accessible-role: table;
    forward-focus: focus-scope;

    VerticalLayout {
        Rectangle {
            clip: true;
            vertical-stretch: 0;
            min-height: root.min-header-height;
            background: Palette.control-background;

            header-layout := HorizontalLayout {
                width: max(self.preferred-width, parent.width);
                x: scroll-view.viewport-x;
                padding-right: 6px;
                min-height: root.min-header-height;

                for column[index] in root.columns: TableViewColumn {
                    sort-order: column.sort-order;
                    horizontal-stretch: column.horizontal-stretch;
                    min-width: max(column.min-width, column.width);
                    preferred-width: self.min-width;
                    max-width: (index < columns.length && column.width >= 1px) ? max(column.min-width, column.width) : 100000px;

                    clicked => {
                        root.sort(index);
                    }

                    adjust-size(diff) => {
                        column.width = max(1px, self.width + diff);
                    }

                    Text {
                        vertical-alignment: center;
                        text: column.title;
                        font-weight: CosmicFontSettings.body.font-weight;
                        font-size: CosmicFontSettings.body.font-size;
                        color: Palette.foreground;
                        overflow: elide;
                    }
                }
            }

            // padding: 5px;

        }

        scroll-view := ListView {
            for file[idx] in root.files: FileTableRow {

                selected: idx == root.current-row;
                even: mod(idx, 2) == 0;

                pointer-event(pe, pos) => {
                    root.row-pointer-event(idx, pe, {
                        x: pos.x - root.absolute-position.x,
                        y: pos.y - root.absolute-position.y,
                    });
                }

                TableViewCell {
                    horizontal-stretch: columns[0].horizontal-stretch;
                    min-width: max(columns[0].min-width, columns[0].width);
                    preferred-width: self.min-width;
                    max-width: (2 < columns.length && columns[0].width >= 1px) ? max(columns[0].min-width, columns[0].width) : 100000px;

                    Rectangle {
                        name-text := Text {
                            width: 100%;
                            height: 100%;
                            overflow: elide;
                            vertical-alignment: center;
                            text: file.name;
                            font-weight: CosmicFontSettings.body.font-weight;
                            font-size: CosmicFontSettings.body.font-size;
                            color: mod(idx, 2) == 0 ? Palette.control-foreground : Palette.foreground;

                            states [
                                selected when idx == root.current-row: {
                                    name-text.color: Palette.accent-background;
                                }
                            ]
                        }
                    }
                }

                TableViewCell {
                    horizontal-stretch: columns[1].horizontal-stretch;
                    min-width: max(columns[1].min-width, columns[1].width);
                    preferred-width: self.min-width;
                    max-width: (1 < columns.length && columns[1].width >= 1px) ? max(columns[1].min-width, columns[1].width) : 100000px;
                    // width: root.column_sizes[1];
                    Rectangle {
                        bytes-text := Text {
                            width: 100%;
                            height: 100%;
                            overflow: elide;
                            vertical-alignment: center;
                            text: root.get-size-next-unit(root.get-size-next-unit(file.size)) + "MBs";
                            font-weight: CosmicFontSettings.body.font-weight;
                            font-size: CosmicFontSettings.body.font-size;
                            color: mod(idx, 2) == 0 ? Palette.control-foreground : Palette.foreground;

                            states [
                                selected when idx == root.current-row: {
                                    bytes-text.color: Palette.accent-background;
                                }
                            ]
                        }
                    }
                }

                TableViewCellNoTouch {
                    horizontal-stretch: columns[2].horizontal-stretch;
                    min-width: max(columns[2].min-width, columns[2].width);
                    preferred-width: self.min-width;
                    max-width: (2 < columns.length && columns[2].width >= 1px) ? max(columns[2].min-width, columns[2].width) : 100000px;
                    // width: root.column_sizes[2];
                    if file.inprogress && !file.failed: ProgressIndicator {
                        indeterminate: false;
                        height: 32px;
                        progress: file.progress / file.size;
                    }
                    if file.failed: Text {
                        text: "FAILED";
                    }

                    if !file.inprogress && !file.failed: Button {
                        text: "Download";
                        clicked => {
                            file.inprogress = true;
                            GameBananaLogic.download(file);
                        }
                    }
                }
            }
        }
    }

    focus-scope := FocusScope {
        x: 0;
        width: 0;
        // Do not react on clicks

        key-pressed(event) => {
            if (event.text == Key.UpArrow) {
                root.set-current-row(root.current-row - 1);
                return accept;
            } else if (event.text == Key.DownArrow) {
                root.set-current-row(root.current-row + 1);
                return accept;
            }
            reject
        }
    }
}
