import { VerticalBox, Palette, Button } from "std-widgets.slint";
import { GameBananaLogic } from "../applogic.slint";
import { GbPreviewData } from "../diva-types.slint";


export component GbPreviewLine {
    in property <GbPreviewData> data;
    in property <int> idx;
    Rectangle {
        background: mod(idx, 2) == 0 ? Palette.background : Palette.alternate-background;
        GridLayout {
            Row {
                Image {
                    source: data.image;
                    height: 62px;
                    width: 110px;
                }

                Text {
                    text: data.name;
                    font-size: 20px;
                    wrap: TextWrap.word-wrap;
                    horizontal-alignment: center;
                    overflow: TextOverflow.elide;
                }

                Text {
                    horizontal-alignment: center;
                    font-size: 14px;
                    overflow: TextOverflow.elide;
                    wrap: TextWrap.word-wrap;
                    text: "Author: " + data.author.name;
                }

                Text {
                    wrap: TextWrap.word-wrap;
                    overflow: TextOverflow.elide;
                    horizontal-alignment: center;
                    font-size: 14px;
                    text: "Type: " + data.item-type;
                }

                Button {
                    text: "Check Files";
                    primary: true;
                    clicked => {
                        GameBananaLogic.list-files(data);
                    }
                }
            }
        }
    }
}

export component GbPreviewCard {
    in property <GbPreviewData> data: {
        image: @image-url("../assets/test-preview.jpg"),
        name:"Onneb's Song Pack",
        author: { name: "Onneb" },
        item-type:"Mod"
    };
    height: 270px;
    width: 236px;
    Rectangle {
        border-width: 1px;
        border-radius: 5px;
        border-color: Palette.border;
        background: Palette.alternate-background;
        VerticalBox {
            alignment: start;
            Image {
                source: data.image;
                height: 124px;
                width: 220px;
            }

            Text {
                text: data.name;
                overflow: TextOverflow.elide;
                font-size: 20px;
                horizontal-alignment: center;
            }

            Text {
                horizontal-alignment: center;
                overflow: TextOverflow.elide;
                font-size: 14px;
                text: "Author: " + data.author.name;
            }

            Text {
                horizontal-alignment: center;
                overflow: TextOverflow.elide;
                font-size: 14px;
                text: "Type: " + data.item-type;
            }

            Button {
                text: "Check Files";
                primary: true;
                clicked => {
                    GameBananaLogic.list-files(data);
                }
            }
        }
    }
}
