import { StandardButton, VerticalBox, Button, AboutSlint, HorizontalBox } from "std-widgets.slint";
import { PopupBorder, Popup } from "../components/popup.slint";


export component InfoDialog {
    in property <string> msg;
    in property <length> offset_x;
    in property <length> offset_y;
    in property <string> r4dversion;
    popup-window := Popup {
        in-out property <length> offset_inner_x;
        x: -368px;
        y: -300px;
        min-win-height: 100px;
        vb := VerticalBox {

            HorizontalLayout {
                Image {

                    height: 256px;
                    width: 256px;
                    source: @image-url("../../assets/rust4diva.png");
                }

                Text {
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    text: "\n\nRust4Diva - Neptune 2024\nFast Cross-platform mod manager for Project Diva Mega Mix+\n\nVersion: " + r4dversion;
                }
            }

            HorizontalBox {
                AboutSlint { }
            }

            Button {
                text: "Ok";
                clicked => {
                    root.close();
                }
            }
        }
    }

    public function show() {
        popup-window.show();
    }

    public function close() {
        popup-window.close();
    }
}
