import { ListView, VerticalBox, ProgressIndicator,CheckBox, Button, Switch  } from "std-widgets.slint";
import { StateLayerBase } from "../components/state-layer-base.slint";
import {Palette, FontSettings} from "../styling.slint";
import { TableViewColumn, TableViewCell, TableViewRow} from "./common-table.slint";
// import {Icons} from ""
import { DivaModElement } from "../diva-types.slint";
import { ModLogic } from "../applogic.slint";


export component ModTableRow inherits Rectangle {
    in property <bool> selected;
    in property <bool> even;
    callback pointer-event(/* event */ PointerEvent, /* absolute mouse position */ Point);

    min-width: layout.min-width;
    min-height: max(24px, layout.min-height);
    background: root.even ? Palette.control-background : transparent;

    layout := HorizontalLayout {
        @children
    }

    StateLayerBase {
        checked: root.selected;
        focus-boder-margin: 0;
        border-radius: root.border-radius;
    }
}

export component ModTable {
    in-out property <[DivaModElement]> mods;
    in-out property <[TableColumn]> columns;
    in-out property <int> current-row: -1;
    out property <int> current-sort-column: -1;
    callback row-pointer-event(int/* row-index */, PointerEvent/* event */, Point/* absolute mouse position */);
    callback current-row-changed(int/* current-row */);
    callback sort-ascending(/* column-index */ int);
    callback sort-descending(/* column-index */ int);
    callback mod-toggled(int, DivaModElement);

    private property <length> min-header-height: 32px;
    private property <length> item-height: scroll-view.viewport-height / mods.length;
    private property <length> current-item-y: scroll-view.viewport-y + current-row * item-height;

    private property <length> e: self.width / root.columns.length;

    public function set-current-row(index: int) {
        if (index < 0 || index >= mods.length) {
            return;
        }
        current-row = index;
        current-row-changed(current-row);

        if (current-item-y < 0) {
            scroll-view.viewport-y += 0 - current-item-y;
        }
        if (current-item-y + item-height > scroll-view.visible-height) {
            scroll-view.viewport-y -= current-item-y + item-height - scroll-view.visible-height;
        }
    }

    function sort(index: int) {
        if (root.current-sort-column != index) {
            root.columns[root.current-sort-column].sort-order = SortOrder.unsorted;
        }
        if (root.columns[index].sort-order == SortOrder.ascending) {
            root.columns[index].sort-order = SortOrder.descending;
            root.sort-descending(index);
        } else {
            root.columns[index].sort-order = SortOrder.ascending;
            root.sort-ascending(index);
        }

        root.current-sort-column = index;
    }

    min-width: 400px;
    min-height: 200px;
    horizontal-stretch: 1;
    vertical-stretch: 1;
    accessible-role: table;
    forward-focus: focus-scope;

    VerticalLayout {
        Rectangle {
            clip: true;
            vertical-stretch: 0;
            min-height: root.min-header-height;
            background: Palette.control-background;

            header-layout := HorizontalLayout {
                width: max(self.preferred-width, parent.width);
                x: scroll-view.viewport-x;
                padding-right: 6px;
                min-height: root.min-header-height;

                for column[index] in root.columns: TableViewColumn {
                    sort-order: column.sort-order;
                    horizontal-stretch: column.horizontal-stretch;
                    min-width: max(column.min-width, column.width);
                    preferred-width: self.min-width;
                    max-width: (index < columns.length && column.width >= 1px) ? max(column.min-width, column.width) : 100000px;

                    clicked => {
                        root.sort(index);
                    }

                    adjust-size(diff) => {
                        column.width = max(1px, self.width + diff);
                    }

                    Text {
                        vertical-alignment: center;
                        text: column.title;
                        font-weight: FontSettings.body.font-weight;
                        font-size: FontSettings.body.font-size;
                        color: Palette.foreground;
                        overflow: elide;
                    }
                }
            }

            // padding: 5px;

        }

        scroll-view := ListView {
            for module[idx] in root.mods: ModTableRow {

                selected: idx == root.current-row;
                even: mod(idx, 2) == 0;

                pointer-event(pe, pos) => {
                    root.row-pointer-event(idx, pe, {
                        x: pos.x - root.absolute-position.x,
                        y: pos.y - root.absolute-position.y,
                    });
                }
                // toggle box
                TableViewCell {
                    horizontal-stretch: columns[0].horizontal-stretch;
                    min-width: max(columns[0].min-width, columns[0].width);
                    preferred-width: self.min-width;
                    max-width: (1 < columns.length && columns[0].width >= 1px) ? max(columns[0].min-width, columns[0].width) : 100000px;
                    Rectangle {
                        mod-toggle := Switch {
                            checked: module.enabled;
                            toggled => {
                                mod-toggled(idx, module);
                            }
                        }
                    }
                }

                // change priority
                TableViewCell {
                    horizontal-stretch: columns[1].horizontal-stretch;
                    min-width: max(columns[1].min-width, columns[1].width);
                    preferred-width: self.min-width;
                    max-width: (1 < columns.length && columns[1].width >= 1px) ? max(columns[1].min-width, columns[1].width) : 100000px;
                    Rectangle {
                        HorizontalLayout {
                            Button {
                                enabled: idx != 0;
                                primary: mod(idx, 2) == 0;
                                icon: @image-url("../assets/up-long-solid.svg");
                                clicked => {
                                    ModLogic.move-mod-up(idx);
                                }
                            }

                            Button {
                                enabled: idx != (mods.length - 1);
                                primary: mod(idx, 2) == 0;
                                icon: @image-url("../assets/down-long-solid.svg");
                                clicked => {
                                    ModLogic.move-mod-down(idx);
                                }
                            }
                        }
                    }
                }

                // name
                TableViewCell {
                    horizontal-stretch: columns[2].horizontal-stretch;
                    min-width: max(columns[2].min-width, columns[2].width);
                    preferred-width: self.min-width;
                    max-width: (2 < columns.length && columns[2].width >= 1px) ? max(columns[2].min-width, columns[2].width) : 100000px;
                    // width: root.column_sizes[0];
                    Rectangle {
                        name-text := Text {
                            width: 100%;
                            height: 100%;
                            overflow: elide;
                            vertical-alignment: center;
                            text: module.name;
                            font-weight: FontSettings.body.font-weight;
                            font-size: FontSettings.body.font-size;
                            color: mod(idx, 2) == 0 ? Palette.control-foreground : Palette.foreground;

                            states [
                                selected when idx == root.current-row: {
                                    name-text.color: Palette.accent-background;
                                }
                            ]
                        }
                    }
                }

                // author
                TableViewCell {
                    horizontal-stretch: columns[3].horizontal-stretch;
                    min-width: max(columns[3].min-width, columns[3].width);
                    preferred-width: self.min-width;
                    max-width: (1 < columns.length && columns[3].width >= 1px) ? max(columns[3].min-width, columns[3].width) : 100000px;
                    // width: root.column_sizes[1];
                    Rectangle {
                        bytes-text := Text {
                            width: 100%;
                            height: 100%;
                            overflow: elide;
                            vertical-alignment: center;
                            text: module.author;
                            font-weight: FontSettings.body.font-weight;
                            font-size: FontSettings.body.font-size;
                            color: mod(idx, 2) == 0 ? Palette.control-foreground : Palette.foreground;

                            states [
                                selected when idx == root.current-row: {
                                    bytes-text.color: Palette.accent-background;
                                }
                            ]
                        }
                    }
                }

                // version
                TableViewCell {
                    horizontal-stretch: columns[4].horizontal-stretch;
                    min-width: max(columns[4].min-width, columns[4].width);
                    preferred-width: self.min-width;
                    max-width: (1 < columns.length && columns[4].width >= 1px) ? max(columns[4].min-width, columns[4].width) : 100000px;
                    // width: root.column_sizes[1];
                    Rectangle {
                        mod-ver := Text {
                            width: 100%;
                            height: 100%;
                            overflow: elide;
                            vertical-alignment: center;
                            text: module.version;
                            font-weight: FontSettings.body.font-weight;
                            font-size: FontSettings.body.font-size;
                            color: mod(idx, 2) == 0 ? Palette.control-foreground : Palette.foreground;

                            states [
                                selected when idx == root.current-row: {
                                    mod-ver.color: Palette.accent-background;
                                }
                            ]
                        }
                    }
                }

                // description
                TableViewCell {
                    horizontal-stretch: columns[5].horizontal-stretch;
                    min-width: max(columns[5].min-width, columns[5].width);
                    preferred-width: self.min-width;
                    max-width: (1 < columns.length && columns[5].width >= 1px) ? max(columns[5].min-width, columns[5].width) : 100000px;

                    Rectangle {
                        mod-desc := Text {
                            width: 100%;
                            height: 100%;
                            overflow: elide;
                            vertical-alignment: center;
                            text: module.description;
                            font-weight: FontSettings.body.font-weight;
                            font-size: FontSettings.body.font-size;
                            color: mod(idx, 2) == 0 ? Palette.control-foreground : Palette.foreground;

                            states [
                                selected when idx == root.current-row: {
                                    mod-desc.color: Palette.accent-background;
                                }
                            ]
                        }
                    }
                }
            }
        }
    }

    focus-scope := FocusScope {
        x: 0;
        width: 0;
        // Do not react on clicks

        key-pressed(event) => {
            if (event.text == Key.UpArrow) {
                root.set-current-row(root.current-row - 1);
                return accept;
            } else if (event.text == Key.DownArrow) {
                root.set-current-row(root.current-row + 1);
                return accept;
            }
            reject
        }
    }
}
