import { PopupBorder, Popup } from "../components/popup.slint";
import { ListView, Button, Palette } from "std-widgets.slint";
import { ModLogic, WindowLogic } from "../applogic.slint";
import { DivaModElement } from "../diva-types.slint";
import { LangTL } from "../applogic.slint";
export component ModCtxMenu {
    in-out property <DivaModElement> module;
    in-out property <Point> pos;
    in-out property <int> idx;
    in property <length> win-height;
    in property <length> win-width;
    popup-window := PopupWindow {
        x: -(win-width / 2) + pos.x;
        y: -(win-height / 2) + (pos.y - 20px);
        width: 100px;
        Rectangle {
            background: Palette.background;
            border-color: Palette.foreground;
            border-width: 1px;
            VerticalLayout {
                padding: 1px;
                width: 100px;
                Rectangle {
                    height: 30px;
                    background: edit-ta.has-hover ? Palette.alternate-background : Palette.background;

                    edit-ta := TouchArea {
                        clicked => {
                            WindowLogic.open-mod-editor(module, idx);
                        }
                        HorizontalLayout {
                            padding-left: 5px;
                            width: 100px;
                            Image {
                                y: 5px;
                                source: @image-url("../assets/file-pen-solid.svg");
                                height: 20px;
                                vertical-alignment: center;
                                width: 20px;
                                colorize: Palette.foreground;
                            }

                            Text {
                                vertical-alignment: center;
                                horizontal-alignment: left;
                                text: LangTL.get-localized-string("button:edit");
                            }
                        }
                    }
                }

                Rectangle {
                    height: 30px;
                    background: delete-ta.has-hover ? Palette.alternate-background : Palette.background;
                    delete-ta := TouchArea {
                        clicked => {
                            ModLogic.delete-mod(module);
                        }
                    }

                    HorizontalLayout {
                        width: 100px;
                        padding-left: 5px;
                        Image {
                            y: 5px;
                            source: @image-url("../assets/trash-can-solid.svg");
                            vertical-alignment: center;
                            width: 20px;
                            height: 20px;
                            colorize: Palette.foreground;
                        }

                        Text {
                            horizontal-alignment: left;
                            vertical-alignment: center;
                            text: LangTL.get-localized-string("button:delete");
                        }
                    }
                }
            }
        }
    }

    public function show(module: DivaModElement, idx: int, pos: Point) {

        self.pos = pos;
        self.module = module;
        self.idx = idx;
        popup-window.show();
    }
}
