import { VerticalBox, Button, Palette, HorizontalBox, StandardButton } from "std-widgets.slint";
import { ModpackLogic, ModLogic } from "../applogic.slint";
import { ConfirmDeleteButton } from "../widgets/buttons.slint";
export component ConfirmDelete inherits Dialog {
    in-out property <string> item;

    callback close();
    callback confirm();

    public function set-color-scheme(scheme: ColorScheme) {
        Palette.color-scheme = scheme;
    }

    title: "Confirm Delete: " + item;

    VerticalBox {
        padding-bottom: 0px;
        Text {
            // min-height: 100px;
            min-width: 200px;
            horizontal-alignment: center;
            vertical-alignment: center;
            text: "Confirm Deletion:\n" + root.item + "";
            font-size: 24px;
        }

        HorizontalBox {
            padding-bottom: 0px;
            ConfirmDeleteButton {
                text: "Confirm";
                // colorize-icon: 
                clicked => {
                    root.confirm();
                }
            }

            Button {
                text: "Cancel";
                clicked => {
                    root.close();
                }
            }
        }
    }
}
