import { VerticalBox, Button, Palette } from "std-widgets.slint";
import { ModpackLogic, ModLogic } from "../applogic.slint";
import { ConfirmDeleteButton } from "../widgets/buttons.slint";
export component ConfirmDeletePack inherits Dialog {
    in-out property <string> modpack;

    callback close();

    public function set-color-scheme(scheme: ColorScheme) {
        Palette.color-scheme = scheme;
    }

    VerticalBox {
        Text {
            // min-height: 100px;
            min-width: 200px;
            horizontal-alignment: center;
            vertical-alignment: center;
            text: "Confirm Deletion:\n" + root.modpack + "";
            font-size: 24px;
        }

        HorizontalLayout {
            ConfirmDeleteButton {
                text: "Confirm";
                clicked => {
                    root.close();
                    ModpackLogic.delete-modpack(root.modpack);
                }
            }

            Button {
                text: "Cancel";
                clicked => {
                    root.close();
                }
            }
        }
    }
}
