import { Button, VerticalBox,HorizontalBox, StandardTableView, TabWidget, TextEdit } from "std-widgets.slint";

export struct SlintModConfig {
    enabled: bool,
    include: [string],
    name: string,
    descrition: string,
    version: string,
    author: string,
    date: string,
    dll: [string]
}

//export component downloads inherits Window {
//    min-width: 1280px;
//    min-height: 720px;
//    title: "Rust4Diva: Project Diva MM+ Mod Manager Mod Search";
//}



export component App inherits Window {
    min-width: 1280px;
    min-height: 720px;
    title: "Rust4Diva: Project Diva MM+ Mod Manager";
    in property <int> counter: 4;
    in property <[int]> fs: [1,2,3];
    in property <[SlintModConfig]> mods: [];
    in property <[[StandardListViewItem]]> stuff: [];
    property window_width <=> self.width;
    property window_height <=> self.height;
    callback load-mods <=> load-mods-btn.clicked;
    callback toggle-mod(int);

//    in-out property mods-table: mod-table;
    default-font-size: 16px;
    VerticalBox {
        Text {
            text: "Goodmorning Mother Fuckers!~~!~~~!";
        }
        TabWidget {
             manager := Tab {
                title: "Manage";
                VerticalBox {
                    mod-table := StandardTableView {
                        min-width: window_width - 12px;
                        height: window_height - 200px;
                        columns: [
                            { title: "Enabled", width: 60px },
                            { title: "Name"},
                            { title: "Authors"},
                            { title: "Version" , width: 60px},
                            { title: "Description" }
                         ];
                        rows: stuff;
                    }
                    HorizontalBox {
                        load-mods-btn := Button {
                            text: "Reload Mods";
                        }
                        toggle-mod-btn := Button {
                            text: "Toggle selected";
                            clicked => {
                                toggle-mod(mod-table.current-row)
                            }
                        }
                    }
                }
            }
            downloads := Tab {
                title: "Search Online";
                VerticalBox {
                    HorizontalBox {
                        search := Text {
                            text: "Search: ";
                        }
                        Rectangle {

                            TextInput {
                                font-size: 22px;
                                wrap: no-wrap;
                                text: "fuck";
                            }
                        }
                    }
                }
            }
        }
    }
}