export struct DivaModElement {
    name: string,
    author: string,
    version: string,
    description: string,
    enabled: bool,
    path: string,
    dirname: string,
}

export struct ModPackElement {
    name: string,
    mods: [DivaModElement],
    path: string,
}


export struct SearchModAuthor {
    name: string,
    avatar_url: string,
}



export enum GbSearchSort {
    default, new, updated,
}

export enum SearchProvider {
    GameBanana, DivaModArchive,
}

export struct Download {
    id: int,
    url: string,
    name: string,
    size: int,
    progress: int,
    failed: bool,
    inprogress: bool,
}
export struct SearchPreviewData {
    name: string,
    author: SearchModAuthor,
    updated: string,
    item-type: string,
    id: int,
    image: image,
    image-url: string,
    image-loaded: bool,
    submitted: string,
    files: [Download],
    preloaded: bool,
}