import { StandardButton } from "std-widgets.slint";
import { CosmicPalette } from "cosmic-styling.slint";


export component ErrorDialog inherits PopupWindow {
    in-out property <string> msg;
    callback ok-cb();
    close-on-click: false;
    min-height: 400px;
    min-width: 600px;
    Rectangle {
        height: 400px;
        width: 600px;
        background: CosmicPalette.alternate-background;
        border-color: CosmicPalette.alternate-border;
        border-radius: 5px;
        opacity: 100%;
        VerticalLayout {
            HorizontalLayout {
                Text {
                    horizontal-alignment: center;
                    text: msg;
                }
            }

            HorizontalLayout {
                StandardButton {
                    width: 100%;
                    kind: ok;
                    clicked => {
                        ok-cb();
                    }
                }
            }
        }
    }
}
