# .github/workflows/build.yml
name: Build

on:
  push:
    branches: [ "*" ]

jobs:
  build-linux:
    name: Build Linux x86_64
    runs-on: ubuntu-latest
    env: 
      SLINT_ENABLE_EXPERIMENTAL_FEATURES: "1" 
    steps:
      - uses: actions/checkout@master

      - name: "Run slugify"
        id: slugify
        uses: eltimn/slugify-action@v2.0.2

      - name: install libarchive
        run: sudo apt install libarchive-dev -y

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ runner.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --verbose

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust4diva-${{steps.slugify.outputs.sha}}-linux-x86_64
          path: target/debug/rust4diva

  build-macos-x86_64:
    name: Build MacOS x86_64
    runs-on: macos-13    
    env: 
      PKG_CONFIG_PATH: "/usr/local/opt/libarchive/lib/pkgconfig"
      SLINT_ENABLE_EXPERIMENTAL_FEATURES: "1" 
    steps:
      - uses: actions/checkout@master
      - name: "Run slugify"
        id: slugify
        uses: eltimn/slugify-action@v2.0.2
      - name: Install libarchive
        run: brew install libarchive
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ runner.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build Rust4Diva
        run: cargo build --verbose

      - name: Bundle Rust4Diva
        run: cargo bundle

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust4diva-${{steps.slugify.outputs.sha}}-macos-${{ runner.arch }}
          path: target/debug/bundle/app/*
  build-macos-arm:
    name: Build MacOS Arm
    runs-on: macos-14    
    env: 
      PKG_CONFIG_PATH: "/usr/local/opt/libarchive/lib/pkgconfig"
      SLINT_ENABLE_EXPERIMENTAL_FEATURES: "1" 
    steps:
      - uses: actions/checkout@master

      - name: "Run slugify"
        id: slugify
        uses: eltimn/slugify-action@v2.0.2

      - name: Install libarchive
        run: brew install libarchive

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ runner.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build Rust4Diva
        run: cargo build --verbose
      - name: Bundle Rust4Diva
        run: cargo bundle
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust4diva-${{steps.slugify.outputs.sha}}-macos-${{ runner.arch }}
          path: target/debug/bundle/app/*

  build-windows-x86_64:
    name: Build Windows x86_64
    runs-on: windows-latest  
    env: 
      SLINT_ENABLE_EXPERIMENTAL_FEATURES: "1" 
      VCPKG_ROOT: "${{ github.workspace }}\\vcpkg"
      VCPKG_DEFAULT_TRIPLET: "x64-windows-static-md"
    steps:
      - uses: actions/checkout@master

      - name: "Run slugify"
        id: slugify
        uses: eltimn/slugify-action@v2.0.2

      - name: vcpkg libarchive
        uses: johnwason/vcpkg-action@v6
        id: vcpkg
        with: 
          pkgs: libarchive
          triplet: x64-windows-static-md
          token: ${{ github.token }}
          github-binarycache: true
      
      - name: Build Rust4Diva
        run: cargo build --verbose

      - name: Package installer
        run: windows\package-nightly.bat

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust4diva-${{steps.slugify.outputs.sha}}-windows-x86_64
          path: windows/output/*