# .github/workflows/build.yml
name: Build

on:
  push:
    branches: [ "*" ]

jobs:
  build-linux:
    name: Build Linux x86_64
    runs-on: ubuntu-latest
    env: 
      SLINT_ENABLE_EXPERIMENTAL_FEATURES: "1" 
    steps:
      - uses: actions/checkout@master
      - name: install libarchive
        run: sudo apt install libarchive-dev -y
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build --verbose
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust4diva${{ github.head_ref }}-linux-x86_64
          path: target/debug/rust4diva
  build-macos-x86_64:
    name: Build MacOS x86_64
    runs-on: macos-13    
    env: 
      PKG_CONFIG_PATH: "/usr/local/opt/libarchive/lib/pkgconfig"
      SLINT_ENABLE_EXPERIMENTAL_FEATURES: "1" 
    steps:
      - uses: actions/checkout@master
      - name: Install libarchive
        run: brew install libarchive
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build Rust4Diva
        run: cargo build --verbose
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust4diva${{ github.head_ref }}-macos-x86_64
          path: target/debug/rust4diva
  build-macos-arm:
    name: Build MacOS Arm
    runs-on: macos-14    
    env: 
      PKG_CONFIG_PATH: "/usr/local/opt/libarchive/lib/pkgconfig"
      SLINT_ENABLE_EXPERIMENTAL_FEATURES: "1" 
    steps:
      - uses: actions/checkout@master

      - name: Install libarchive
        run: brew install libarchive
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build Rust4Diva
        run: cargo build --verbose
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust4diva${{ github.head_ref }}-macos-arm
          path: target/debug/rust4diva
  build-windows-x86_64:
    name: Build Windows x86_64
    runs-on: windows-latest  
    env: 
      SLINT_ENABLE_EXPERIMENTAL_FEATURES: "1" 
      VCPKG_ROOT: "C:\\vcpkg"
      VCPKG_DEFAULT_TRIPLET: "x64-windows-static-md"
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v4
        id: cache
        with:
          path: "C:\\vcpkg\\installed\\x64-windows-static-md"
          key: ${{ runner.os }}-${{ hashFiles('windows/libarchive.dll') }}
      - name: Setup libarchive
        uses: lukka/run-vcpkg@v11
        id: runvcpkg
        with:
          # This one is not needed, as it is the default value anyway.
          # vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgJsonGlob: 'windows/vcpkg.json'
      - name: Build Rust4Diva
        run: cargo build --verbose
      - name: Package installer
        run: windows\package-nightly.bat
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust4diva${{ github.head_ref }}-windows-x86_64
          path: windows/output/*