# .github/workflows/build.yml
name: Build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install libarchive
        run: sudo apt install libarchive-dev -y
      - name: Build
        run: SLINT_ENABLE_EXPERIMENTAL_FEATURES=1 cargo build --verbose
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: rust4diva${{ github.head_ref }}-linux.zip
          path: target/debug/rust4diva
