# .github/workflows/build.yml
name: Build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install libarchive
        run: apt install libarchive-dev -y
      - name: Build
        run: cargo build --verbose
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: rust4diva${{ github.head_ref }}.zip
          path: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}
