# .github/workflows/build.yml
name: Build Release

on:
  release:
    types: [published]

jobs:
  build-linux:
    name: Build Linux x86_64
    runs-on: ubuntu-latest
    env: 
      SLINT_ENABLE_EXPERIMENTAL_FEATURES: "1" 
    steps:
      - uses: actions/checkout@master

      - name: install libarchive
        run: sudo apt install libarchive-dev -y

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ runner.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --verbose --release

      - name: Make sure Cargo-bundle installed
        continue-on-error: true
        run: cargo install cargo-bundle

      - name: Bundle Rust4Diva
        run: cargo bundle --release

      - name: Upload release executable
        uses: actions/upload-artifact@v4
        with:
          name: rust4diva-${{ github.event.release.tag_name}}-linux-x86_64
          path: target/release/rust4diva
      - name: Upload deb
        uses: actions/upload-artifact@v4
        with:
          name: rust4diva-${{ github.event.release.tag_name}}-linux-x86_64-deb
          path: target/release/bundle/deb/*
      - name: Upload To Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          path: target/release/bundle/deb/*

  build-macos-x86_64:
    name: Build MacOS x86_64
    runs-on: macos-13    
    env: 
      PKG_CONFIG_PATH: "/usr/local/opt/libarchive/lib/pkgconfig"
      SLINT_ENABLE_EXPERIMENTAL_FEATURES: "1" 
      MACOSX_DEPLOYMENT_TARGET: "10.12"
    steps:
      - uses: actions/checkout@master

      - name: Install libarchive
        run: brew install libarchive

      - name: Install Create-DMG
        run: brew install create-dmg

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ runner.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          
      - name: Build Rust4Diva
        run: cargo build --verbose --release
      
      - name: Create IconSet
        run: iconutil -c icns assets/icon.iconset

      - name: Setup Cargo Bundle
        continue-on-error: true
        run: cargo install cargo-bundle 

      - name: Bundle Rust4Diva
        run: cargo bundle --release
        
      - name: Create DMG image
        run: create-dmg --volname "Rust4Diva" --volicon "assets/icon.icns" --window-pos 200 120 --window-size 800 400 --icon-size 100 --icon "Rust4Diva.app" 200 190 --hide-extension "Rust4Diva.app" --app-drop-link 600 185 "rust4diva-${{ github.event.release.tag_name}}-macos-${{ runner.arch }}.dmg" "target/release/bundle/osx"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust4diva-${{ github.event.release.tag_name}}-macos-${{ runner.arch }}
          path: rust4diva-${{ github.event.release.tag_name}}-macos-${{ runner.arch }}.dmg
      - name: Upload To Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          path: rust4diva-${{ github.event.release.tag_name}}-macos-${{ runner.arch }}.dmg
  build-macos-arm:
    name: Build MacOS Arm
    runs-on: macos-14    
    env: 
      PKG_CONFIG_PATH: "/usr/local/opt/libarchive/lib/pkgconfig"
      SLINT_ENABLE_EXPERIMENTAL_FEATURES: "1" 
      MACOSX_DEPLOYMENT_TARGET: "10.12"
    steps:
      - uses: actions/checkout@master

      - name: Install libarchive
        run: brew install libarchive

      - name: Install Create-DMG
        run: brew install create-dmg

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ runner.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build Rust4Diva
        run: cargo build --verbose --release
      - name: Create IconSet
        run: iconutil -c icns assets/icon.iconset

      - name: Setup Cargo Bundle
        continue-on-error: true
        run: cargo install cargo-bundle

      - name: Bundle Rust4Diva
        run: cargo bundle --release
      - name: Create DMG image
        run: create-dmg --volname "Rust4Diva" --volicon "assets/icon.icns" --window-pos 200 120 --window-size 800 400 --icon-size 100 --icon "Rust4Diva.app" 200 190 --hide-extension "Rust4Diva.app" --app-drop-link 600 185 "rust4diva-${{ github.event.release.tag_name}}-macos-${{ runner.arch }}.dmg" "target/release/bundle/osx"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust4diva-${{ github.event.release.tag_name}}-macos-${{ runner.arch }}
          path: rust4diva-${{ github.event.release.tag_name}}-macos-${{ runner.arch }}.dmg
      - name: Upload To Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          path: rust4diva-${{ github.event.release.tag_name}}-macos-${{ runner.arch }}.dmg

  build-windows-x86_64:
    name: Build Windows x86_64
    runs-on: windows-latest  
    env: 
      SLINT_ENABLE_EXPERIMENTAL_FEATURES: "1" 
      VCPKG_ROOT: "${{ github.workspace }}\\vcpkg"
      VCPKG_DEFAULT_TRIPLET: "x64-windows-static-md"
    steps:
      - uses: actions/checkout@master

      - name: vcpkg libarchive
        uses: johnwason/vcpkg-action@v6
        id: vcpkg
        with: 
          pkgs: libarchive
          triplet: x64-windows-static-md
          token: ${{ github.token }}
          github-binarycache: true
      
      - name: Build Rust4Diva
        run: cargo build --verbose --release

      - name: Package installer
        run: windows\package-release.bat

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust4diva-${{ github.event.release.tag_name}}-windows-x86_64
          path: windows/output/*
      - name: Upload To Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          name: rust4diva-${{ github.event.release.tag_name}}-windows-x86_64
          path: windows/output/*